stellar contract invoke \
  --id CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA \
  --source-account ambar \
  --network testnet \
  -- \
  allowance \
  --from GCRHESVKSSJ3TKXP5BRBPTI7M5OKYULKBX7LBXRLSG7C5SNOD6U74KUH \
  --spender GC24UCPAU5OIEVZBJZRSQYENKA4BMFSSZ53MHN3CARQI2N22XCI4OKMJ
