stellar contract invoke \
  --id CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA \
  --source-account ambar-contract \
  --network testnet \
  --send yes \
  -- \
  transfer_from \
  --from GCRHESVKSSJ3TKXP5BRBPTI7M5OKYULKBX7LBXRLSG7C5SNOD6U74KUH \
  --spender CA22K2BNEKDPGOC2VSRK3RG5D6DO5EMNCD6GXOWMT3SUMALVYL4AANFL \
  --to GC24UCPAU5OIEVZBJZRSQYENKA4BMFSSZ53MHN3CARQI2N22XCI4OKMJ \
  --amount 5 
